name: run
on: 
  schedule:
    - cron: '57 15 * * *' 
  push:
    branches: [main]
jobs:
  run_script_and_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v3
    - name: 设置环境
      run: |
        sudo apt-get update
        sudo apt-get install -y tzdata
        sudo apt-get install -y language-pack-zh-hans
        export LANG=zh_CN.UTF-8
        export LC_ALL=zh_CN.UTF-8
        sudo timedatectl set-timezone Asia/Shanghai
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Install python dependencies
      run: |
        conda info
        echo "========================"
        conda list
        conda env list
        echo "========================"
        playwright install chrome
    - name: Run tests
      run: |
        python3 main.py
    - name: delete
      run: |
        rm -rf ~/Default
  
    - name: update 
      run: |
        git config --global user.email "zoushucai"
        git config --global user.name "zoushucai@users.noreply.github.com"
        git add .
        git commit -m "Update"
        git push origin main